version: "3.3"

services:
  server:
    ports:
      - 3333:3333
    networks:
      - internal_world
    build:
      context: packages/server
      dockerfile: Dockerfile
    volumes:
      - ./packages/server:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - ./packages/server/.env
    environment:
      - MONGO_URL=db

  db:
    image: mongo
    networks:
      - internal_world
    volumes:
      - /deploy/databases/rep_finances_db:/data/db

networks:
  internal_world:
    external: true
